source 'https://github.com/CocoaPods/Specs.git'

target 'DWSwitch', :exclusive => true do
  pod "DWSwitch", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DWSwitch", :path => "../"

  
end
